
name: Compilar proyecto "Presentaciones Interactivas"

on:
  
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:

  build:
    env:
    
      SPECFLOW_PROJECT: PresInteractivas.Test
      
    runs-on: ubuntu-latest
    container: breinergonza/mono:test
    
    steps:
      
      - name: Checkout project
        uses: actions/checkout@v2
  
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test
      
      - name:  Instalar generador de documentacion
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
      
      - name: Generate LivingDoc documentation
        run: |
          export PATH="$PATH:/github/home/.dotnet/tools"
          livingdoc test-assembly ./$SPECFLOW_PROJECT/bin/Debug/net5.0/$SPECFLOW_PROJECT.dll -t ./$SPECFLOW_PROJECT/bin/Debug/net5.0/TestExecution.json --output ./docs/index.html
          
      - name: Instalar Rsync
        run: sudo apt-get install -y rsync 
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./docs 
        